#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: take "staged" ssh keys and put them in the home directory

set -e
set -o xtrace

yum -y install openssh-server openssh-client

dd if=/tmp/in_target.d/authorized_keys of=/home/trove/.ssh/authorized_keys
