#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

# Copy MariaDB .repo file
dd if=/tmp/in_target.d/mariadb.repo of=/etc/yum.repos.d/mariadb.repo

yum -y install mariadb
