#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum -y install gcc python-pip python-pexpect MySQL-python python-devel libxml2-devel libxslt-devel wget
