#!/bin/bash

set -e
set -o xtrace

if [ "${DISTRO}" = "rhel" ]; then
  # NOTE(vkmc) This is necessary for now. Waiting for the release.
  yum -y install wget
  wget http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm
  yum -y --nogpgcheck localinstall rhos-release-latest.noarch.rpm
  rhos-release 7
fi

if [ "${DISTRO}" = "centos" ]; then
  yum -y install https://rdo.fedorapeople.org/rdo-release.rpm wget
  yum -y update
  sed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers
fi

yum -y install openstack-trove-guestagent python-troveclient python-netifaces pexpect
