#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

# yum install -y mongodb mongodb-server

dd if=/tmp/in_target.d/mongodb26.repo of=/etc/yum.repos.d/mongodb26.repo

yum install -y mongodb-org mongodb-org-server

# the following config changes are needed: smallfiles set to true, and bind_ip
# set to default
sed -i '/bind_ip/d' /etc/mongod.conf
sed -i '/smallfiles/d' /etc/mongod.conf
echo 'smallfiles = true' >> /etc/mongod.conf
