#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum -y install mysql mysql-server

# Enable and start the MySQL server
systemctl enable mariadb.service
systemctl start mariadb.service
