#!/bin/bash

set -e
set -o xtrace

# Copy service file
dd if=/tmp/in_target.d/openstack-trove-guestagent.service of=/usr/lib/systemd/system/openstack-trove-guestagent.service

# Configuring permissions
mkdir -p /etc/trove/conf.d
chown -R trove:trove /etc/trove
chown trove:trove /usr/share/trove
chown trove:trove /var/log/trove

# Enable and start service
systemctl enable openstack-trove-guestagent.service
systemctl start openstack-trove-guestagent.service
